### ISSUE TITLE
Pi Cycle Top Indicator

### ISSUE THREAD

**Issue by nicholasp** [Zaczero/btcpredict#1]
Great work man!! Thanks for sharing. You should reconsider Pi Cycle Top Indicator. For this bull market the reflexivity is much higher than past cycles. Seems it doesn't work this indicator.

**Comment by Zaczero** [comment]
While I may consider this suggestion in the future, I believe it is still too early to make such a judgement. Let's come back to this issue in at least 1 month from now.

**Comment by Zaczero** [comment]
I think we all agree on leaving the Pi Cycle indicator in the game based on the last week's price changes :octocat: .
