### ISSUE TITLE
Backtesting

### ISSUE THREAD

**Issue by carlosmassa** [Zaczero/btcpredict#2]
Hey, great project! Thanks for sharing the code!!

I was wondering if you have done any backtesting to check the performance predicting previous cycle tops with prior data up to certain stages within a cycle. For instance, checking what the code predicts with data up to Jan 2017, up to Apr 2017, up to Jul 2017 and up to Oct 2017.

**Comment by Zaczero** [comment]
Hey, in this message I'll present you the numbers for the previous 2017 bull run. I just want you to have in mind that there is not much data to work on and by attempting to predict previous bull run we are basing our numbers on just the 2013 bull run. In other words, **the modified model is most likely over-fitted** (just 336 training rows). The more data we get, the more stable the model will be.

It's also important to note that **during 2017 bull run Bitcoin has reached its block size limit** which most likely reduced its upside movement potential in compare to the previous 2013 bull run. **The model predicts based on the historical data** and when the training data contains no info regarding block fullness we are stepping into an uncharted territory.

_200 days before peak:_
price: 20,000$
date: +203 days

_100 days before peak:_
price: 28,000$
date: +102 days

_30 days before peak:_
price: 37,600$
date: +31 days

Code changes required to predict 2017 bull run (added lines 339, 340):
![210424190249_pycharm64_4d591d](https://user-images.githubusercontent.com/10835147/115966842-f2709b00-a51e-11eb-8fd8-ada72f4a3c41.png)

**Comment by carlosmassa** [comment]
Thanks for the comprehensive reply. I understand that the model predicts based on the historical data, and that the more data we have, the better the prediction will be. However, in the back testing you show for the 2017 top prediction, the most accurate prediction was 200 days before the top:

200 days before peak:
price: 20,000$
date: +203 days

And then, the closer to the actual top date, the higher the prediction was:

100 days before peak:
price: 28,000$
date: +102 days

30 days before peak:
price: 37,600$
date: +31 days

Could this be because the model was adding rising values to the data? It would be interesting to see a plot of the predicted price and time of the top as time goes by.

Again, great project and I'm very eager to see how it performs this time!

**Comment by Zaczero** [comment]
> Could this be because the model was adding rising values to the data?

Nope, the model calculates the percentage of the current bull run peak value. E.g. if price is 10,000$ and predicted peak is at 20,000$ the model would return 50% for the given row. This way 10,000$ / 50% = 20,000$. The reason for such discrepancy, towards the end of 2017 bull run, would most likely be not enough of training data. It just failed to generalize enough.

In the updated price prediction model (today) I have added one more column which strongly correlates with the date of the bull run peak. It should hopefully make the prediction more reliable as we approach the peak.

https://github.com/Zaczero/btcpredict/blob/main/predictor/main.py#L404

**Comment by carlosmassa** [comment]
> It should hopefully make the prediction more reliable as we approach the peak.

Is it possible to back test again after the updated price prediction model you just did to see what is the impact in the price predictions below for the 2017 cycle?

200 days before peak:
price: 
date: 

100 days before peak:
price: 
date: 

30 days before peak:
price: 
date:

**Comment by carlosmassa** [comment]
> 
> 
> Hey, in this message I'll present you the numbers for the previous 2017 bull run. I just want you to have in mind that there is not much data to work on and by attempting to predict previous bull run we are basing our numbers on just the 2013 bull run. In other words, **the modified model is most likely over-fitted** (just 336 training rows). The more data we get, the more stable the model will be.
> 
> It's also important to note that **during 2017 bull run Bitcoin has reached its block size limit** which most likely reduced its upside movement potential in compare to the previous 2013 bull run. **The model predicts based on the historical data** and when the training data contains no info regarding block fullness we are stepping into an uncharted territory.
> 
> _200 days before peak:_
> price: 20,000$
> date: +203 days
> 
> _100 days before peak:_
> price: 28,000$
> date: +102 days
> 
> _30 days before peak:_
> price: 37,600$
> date: +31 days
> 
> Code changes required to predict 2017 bull run (added lines 339, 340):
> ![210424190249_pycharm64_4d591d](https://user-images.githubusercontent.com/10835147/115966842-f2709b00-a51e-11eb-8fd8-ada72f4a3c41.png)

Another question I just thought of is why do you only take data from 2015-01-15 (previous bottom) to predict the 2017 cycle top? Wouldn't it be better to take data since as back as possible? Price data is available since July/August 2010. Wouldn't this added data help train better the model, since it also would include two full cycles with its tops and bottoms?

**Comment by Zaczero** [comment]
Labels after 2015-01-15 are set to NaN. This data is what we predict in 2017 bull run and thus we are unable to know it. The actual training data is everything starting from 2011-01-01. So for 2017 bull run it would be 2011-01-01 - 2015-01-14. Earlier (pre-2011) data seems too much unrelated with current bull runs, there is too much noise in it. It would just hurt overall model performance.

Data range starting from - line:
https://github.com/Zaczero/btcpredict/blob/main/predictor/main.py#L51

**Comment by Zaczero** [comment]
@carlosmassa Can this issue be closed now?

**Comment by carlosmassa** [comment]
> @carlosmassa Can this issue be closed now?

Yes, many thanks for your comments.
